import { LightningElement, api, track } from "lwc";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import getCoworkerStatus from "@salesforce/apex/AgentforceController.getCoworkerStatus";
import explainArtifact from "@salesforce/apex/AgentforceController.explainArtifact";
import { cacheKey, readCache, writeCache, clearCache } from "c/auditCache";

export default class AgentforceAssistant extends LightningElement {
  _isOpen = false;
  @api
  get isOpen() {
    return this._isOpen;
  }
  set isOpen(value) {
    const wasOpen = this._isOpen;
    this._isOpen = value;
    if (value && !wasOpen) {
      this.scheduleAnalysis();
    }
  }

  _artifactName = "";
  @api
  get artifactName() {
    return this._artifactName;
  }
  set artifactName(value) {
    const previous = this._artifactName;
    this._artifactName = value || "";
    if (this._artifactName !== previous) {
      this.scheduleAnalysis();
    }
  }

  _artifactPayload = "";
  @api
  get artifactPayload() {
    return this._artifactPayload;
  }
  set artifactPayload(value) {
    const previous = this._artifactPayload;
    this._artifactPayload = value || "";
    if (this._artifactPayload !== previous) {
      this.scheduleAnalysis();
    }
  }

  @api artifactType = "APEX";

  // Findings computed deterministically from metadata rather than generated.
  // They are rendered separately so they are never at the mercy of the model
  // choosing to repeat them, and are labelled so users know they are exact.
  @api verifiedFindings = "";

  @track status = null;
  @track explanationText = "";
  @track isLoading = false;

  _analysisScheduled = false;
  _requestId = 0;

  // "drawer" sits beside a diagram you are reading; "modal" is for a long
  // report where the panel *is* the task and needs the width.
  @api variant = "drawer";

  // Short factual line under the title (e.g. how much was actually read).
  // Grounds the report in what it saw, which marketing copy cannot do.
  @api scopeSummary = "";

  @track servedFromCacheAt = 0;

  get isCached() {
    return this.servedFromCacheAt > 0;
  }

  get cacheNote() {
    if (!this.isCached) return "";
    const mins = Math.floor((Date.now() - this.servedFromCacheAt) / 60000);
    if (mins < 1) return "cached · just now";
    if (mins < 60) return `cached · ${mins} min ago`;
    const hrs = Math.floor(mins / 60);
    return `cached · ${hrs} hr ago`;
  }

  get analysisCacheKey() {
    if (!this._artifactName) return "";
    return cacheKey([
      this.artifactType,
      this._artifactName,
      this._artifactPayload
    ]);
  }

  get shellClass() {
    return this.variant === "modal"
      ? "assistant-shell assistant-shell_modal slds-is-relative"
      : "assistant-shell assistant-shell_drawer slds-is-relative";
  }

  get isObjectAudit() {
    return (this.artifactType || "").toUpperCase().startsWith("OBJECT");
  }

  get headerIcon() {
    return this.isObjectAudit ? "utility:search" : "utility:einstein";
  }

  // Lead with the subject the user opened, not with the vendor.
  get headerTitle() {
    const name = this.artifactName || "Artifact";
    switch ((this.artifactType || "").toUpperCase()) {
      case "OBJECT":
      case "OBJECT_DEEP":
        return `Automation Audit · ${name}`;
      case "APEX":
        return `Apex Analysis · ${name}`;
      default:
        return `Flow Analysis · ${name}`;
    }
  }

  get artifactTypeLabel() {
    switch ((this.artifactType || "").toUpperCase()) {
      case "OBJECT_DEEP":
        return "Definitions read · flows and Apex";
      case "OBJECT":
        return "Signature-level audit";
      default:
        return `${this.artifactType} artifact`;
    }
  }

  get analysisHeading() {
    return this.isObjectAudit ? "Analysis" : "Explanation";
  }

  // Provenance sits with the generated content, not over the whole panel.
  get analysisProvenance() {
    if (!this.status) return "";
    return this.status.isAvailable
      ? "generated by Agentforce Coworker"
      : "AI unavailable in this org";
  }

  get showUnavailableNotice() {
    return !!this.status && !this.status.isAvailable;
  }

  /**
   * Counts severity tags across both the computed and generated findings, so
   * the reader sees the shape of the report before scrolling it.
   */
  get severitySummary() {
    const text = `${this.verifiedFindings || ""}\n${this.explanationText || ""}`;
    return ["HIGH", "MEDIUM", "LOW"]
      .map((level) => ({
        label: level,
        count: (text.match(new RegExp(`\\[${level}\\]`, "g")) || []).length,
        cssClass: `severity-chip severity-chip_${level.toLowerCase()}`
      }))
      .filter((s) => s.count > 0);
  }

  get hasSeveritySummary() {
    return !this.isLoading && this.severitySummary.length > 0;
  }

  /**
   * Models frequently wrap an entire markdown answer in a ```markdown fence.
   * Left in place it would render as one big code block, so unwrap it — but
   * only when the fence really does enclose the whole response.
   */
  stripOuterFence(text) {
    const trimmed = (text || "").trim();
    const match = trimmed.match(/^```(markdown|md)?[ \t]*\n([\s\S]*?)\n?```$/i);
    if (!match) return text;
    // An unlabeled fence is only unwrapped when the content is clearly prose.
    if (!match[1] && !/^#{1,6}[ \t]/m.test(match[2])) return text;
    return match[2];
  }

  parseMarkdown(text) {
    if (!text) return "";
    let formatted = this.stripOuterFence(text);

    // Fenced Code blocks ```lang ... ```
    formatted = formatted.replace(
      /```[a-z]*\n([\s\S]*?)\n```/gim,
      (match, code) => {
        const escaped = code
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        return `<pre class="code-block"><code>${escaped}</code></pre>`;
      }
    );

    // Headings (##### down to #)
    formatted = formatted.replace(
      /^#####[ \t]+(.*$)/gim,
      '<h5 class="markdown-h5">$1</h5>'
    );
    formatted = formatted.replace(
      /^####[ \t]+(.*$)/gim,
      '<h4 class="markdown-h4">$1</h4>'
    );
    formatted = formatted.replace(
      /^###[ \t]+(.*$)/gim,
      '<h3 class="markdown-h3">$1</h3>'
    );
    formatted = formatted.replace(
      /^##[ \t]+(.*$)/gim,
      '<h2 class="markdown-h2">$1</h2>'
    );
    formatted = formatted.replace(
      /^#[ \t]+(.*$)/gim,
      '<h1 class="markdown-h1">$1</h1>'
    );

    // Bold & Inline Code
    formatted = formatted.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
    formatted = formatted.replace(/`([^`]+)`/g, "<code>$1</code>");

    // GitHub alert quotes
    formatted = formatted.replace(
      /> \[!NOTE\]\n> (.*)/gi,
      '<div class="slds-notify slds-notify_alert slds-alert_warning" role="alert"><span class="slds-assistive-text">info</span><h2>$1</h2></div>'
    );

    // List items (bullets and numbered lists)
    formatted = formatted.replace(/^[ \t]*[-*][ \t]+(.*$)/gim, "<li>$1</li>");
    formatted = formatted.replace(/^[ \t]*\d+\.[ \t]+(.*$)/gim, "<li>$1</li>");

    // Line breaks
    formatted = formatted.replace(/\n\n/g, "<br/><br/>");
    formatted = formatted.replace(/\n/g, "<br/>");

    return formatted;
  }

  get hasVerifiedFindings() {
    return !!this.verifiedFindings;
  }

  get formattedVerifiedFindings() {
    return this.parseMarkdown(this.verifiedFindings);
  }

  get formattedExplanation() {
    return this.parseMarkdown(this.explanationText);
  }

  connectedCallback() {
    if (this.isOpen) {
      this.scheduleAnalysis();
    }
  }

  /**
   * The parent sets isOpen, artifactName and artifactPayload in the same
   * rehydration tick, so coalesce those into a single analysis that runs once
   * every property has landed.
   */
  scheduleAnalysis() {
    if (this._analysisScheduled) return;
    this._analysisScheduled = true;
    Promise.resolve().then(() => {
      this._analysisScheduled = false;
      if (this._isOpen && this._artifactName) {
        this.checkStatusAndAnalyze();
      }
    });
  }

  async checkStatusAndAnalyze(bypassCache = false) {
    if (!this.artifactName) return;

    const key = this.analysisCacheKey;
    if (bypassCache) {
      clearCache(key);
    } else {
      // Same artifact, same payload, same prompt version — nothing a model
      // call would add. This covers both the object audit and Explain Artifact.
      const hit = readCache(key);
      if (hit) {
        this.explanationText = hit.explanation;
        this.status = { isAvailable: hit.aiAvailable };
        this.servedFromCacheAt = hit.cachedAt;
        this.isLoading = false;
        return;
      }
    }

    this.isLoading = true;
    this.explanationText = "";
    this.servedFromCacheAt = 0;

    // Discard a response that arrives after the artifact has moved on.
    const requestId = ++this._requestId;

    try {
      const status = await getCoworkerStatus();
      const result = await explainArtifact({
        artifactType: this.artifactType,
        artifactName: this.artifactName,
        artifactPayload: this.artifactPayload || ""
      });

      if (requestId !== this._requestId) return;
      this.status = status;
      this.explanationText = result.explanation;
      writeCache(key, {
        explanation: result.explanation,
        aiAvailable: status.isAvailable,
        cachedAt: Date.now()
      });
    } catch (err) {
      if (requestId !== this._requestId) return;
      this.explanationText = `Failed to generate explanation: ${err.body?.message || err.message || err}`;
    } finally {
      if (requestId === this._requestId) {
        this.isLoading = false;
      }
    }
  }

  handleClose() {
    this.dispatchEvent(new CustomEvent("close"));
  }

  handleRerun() {
    // Let the parent rebuild an expensive payload if it wants to; otherwise
    // just regenerate here, bypassing the cached response.
    this.dispatchEvent(new CustomEvent("rerun"));
    this.checkStatusAndAnalyze(true);
  }

  /**
   * An audit costs real time and model spend, so let the reader keep it.
   * Copies the markdown source rather than the rendered HTML.
   */
  async handleCopyReport() {
    const parts = [`# ${this.headerTitle}`];
    if (this.scopeSummary) parts.push(this.scopeSummary);
    if (this.verifiedFindings) {
      parts.push(
        "## Verified findings\n_Computed from metadata, not AI-generated._\n",
        this.verifiedFindings
      );
    }
    if (this.explanationText) {
      const provenance = this.analysisProvenance
        ? `_${this.analysisProvenance}_\n`
        : "";
      parts.push(
        `## ${this.analysisHeading}\n${provenance}`,
        this.explanationText
      );
    }
    const report = parts.join("\n\n");

    try {
      await navigator.clipboard.writeText(report);
      this.dispatchEvent(
        new ShowToastEvent({
          title: "Report copied",
          message: "The audit was copied to your clipboard as markdown.",
          variant: "success"
        })
      );
    } catch {
      this.dispatchEvent(
        new ShowToastEvent({
          title: "Could not copy",
          message: "Your browser blocked clipboard access.",
          variant: "warning"
        })
      );
    }
  }
}
