import { createElement } from "lwc";
import AgentforceAssistant from "c/agentforceAssistant";
import explainArtifact from "@salesforce/apex/AgentforceController.explainArtifact";
import getCoworkerStatus from "@salesforce/apex/AgentforceController.getCoworkerStatus";

jest.mock(
  "@salesforce/apex/AgentforceController.explainArtifact",
  () => ({ default: jest.fn() }),
  { virtual: true }
);
jest.mock(
  "@salesforce/apex/AgentforceController.getCoworkerStatus",
  () => ({ default: jest.fn() }),
  { virtual: true }
);

// Real-shaped cache with a per-test store, so one test cannot serve another's
// result and each starts from a cold cache.
jest.mock(
  "c/auditCache",
  () => {
    const store = new Map();
    const hashString = (text) => {
      let h = 0;
      for (let i = 0; i < String(text || "").length; i++) {
        h = (h * 31 + String(text).charCodeAt(i)) | 0;
      }
      return String(h >>> 0);
    };
    return {
      PROMPT_VERSION: 1,
      hashString,
      cacheKey: (parts) => "k:" + hashString(parts.join("|")),
      readCache: (k) => (store.has(k) ? store.get(k) : null),
      writeCache: (k, v) => store.set(k, v),
      clearCache: (k) => store.delete(k),
      __store: store
    };
  },
  { virtual: true }
);

describe("c-agentforce-assistant", () => {
  beforeEach(() => {
    require("c/auditCache").__store.clear();
  });

  afterEach(() => {
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
    jest.clearAllMocks();
  });

  async function flushPromises() {
    // eslint-disable-next-line @lwc/lwc/no-async-operation -- test-only flush
    return new Promise((resolve) => setTimeout(resolve, 0));
  }

  function build(props = {}) {
    const element = createElement("c-agentforce-assistant", {
      is: AgentforceAssistant
    });
    Object.assign(element, props);
    document.body.appendChild(element);
    return element;
  }

  async function open(props = {}) {
    const element = build({
      artifactType: "OBJECT_DEEP",
      artifactName: "Opportunity",
      artifactPayload: "payload",
      ...props,
      isOpen: true
    });
    await flushPromises();
    await flushPromises();
    return element;
  }

  beforeEach(() => {
    getCoworkerStatus.mockResolvedValue({
      isAvailable: true,
      statusMessage: "Agentforce Coworker is active and ready."
    });
    explainArtifact.mockResolvedValue({
      explanation: "### Verdict\nHigh Risk\n\n#### [HIGH] Something\n"
    });
  });

  it("leads the header with the subject, not the vendor", async () => {
    const element = await open({
      scopeSummary: "32 automations · 30 flow definitions read"
    });

    const title = element.shadowRoot.querySelector(".assistant-title");
    expect(title.textContent).toBe("Automation Audit · Opportunity");

    // The subtitle states scope, replacing the old marketing line.
    const subtitle = element.shadowRoot.querySelector(".assistant-subtitle");
    expect(subtitle.textContent).toBe(
      "32 automations · 30 flow definitions read"
    );

    // No panel-wide AI badge: provenance is per section now.
    expect(element.shadowRoot.querySelector(".badge-active")).toBeNull();
  });

  it("attributes only the generated section to Agentforce", async () => {
    const element = await open({
      verifiedFindings: "#### [HIGH] Field contention on `Rating`"
    });

    // Computed block says it is not AI.
    const verified = element.shadowRoot.querySelector(
      ".verified-findings-card .provenance-note"
    );
    expect(verified.textContent).toBe(
      "computed from metadata, not AI-generated"
    );

    // Generated block carries the AI attribution.
    const analysis = element.shadowRoot.querySelector(
      ".analysis-header .provenance-note"
    );
    expect(analysis.textContent).toBe("generated by Agentforce Coworker");
  });

  it("says AI is unavailable without disowning the computed findings", async () => {
    getCoworkerStatus.mockResolvedValue({
      isAvailable: false,
      statusMessage: "Agentforce Coworker is not enabled."
    });
    explainArtifact.mockResolvedValue({ explanation: "structural summary" });

    const element = await open({
      verifiedFindings: "#### [HIGH] Field contention on `Rating`"
    });

    expect(
      element.shadowRoot.querySelector(".analysis-header .provenance-note")
        .textContent
    ).toBe("AI unavailable in this org");
    // The computed findings are still rendered and still labelled as exact.
    expect(
      element.shadowRoot.querySelector(".verified-findings-card")
    ).not.toBeNull();
    expect(element.shadowRoot.querySelector(".env-banner")).not.toBeNull();
  });

  it("summarises severity across computed and generated findings", async () => {
    explainArtifact.mockResolvedValue({
      explanation: "#### [HIGH] A\n#### [MEDIUM] B\n#### [LOW] C\n"
    });

    const element = await open({
      verifiedFindings: "#### [HIGH] Field contention on `Rating`"
    });

    const chips = [
      ...element.shadowRoot.querySelectorAll(".severity-chip")
    ].map((c) => c.textContent.trim());
    // Two HIGH: one verified, one generated.
    expect(chips).toEqual(["2 HIGH", "1 MEDIUM", "1 LOW"]);
  });

  it("renders as a modal when asked, and a drawer by default", async () => {
    const modal = await open({ variant: "modal" });
    expect(
      modal.shadowRoot.querySelector(".assistant-shell_modal")
    ).not.toBeNull();
    expect(
      modal.shadowRoot.querySelector(".assistant-shell_drawer")
    ).toBeNull();

    const drawer = await open({ artifactType: "APEX", artifactName: "Foo" });
    expect(
      drawer.shadowRoot.querySelector(".assistant-shell_drawer")
    ).not.toBeNull();
    expect(
      drawer.shadowRoot.querySelector(".assistant-shell_modal")
    ).toBeNull();
    // Non-object artifacts keep their own title shape.
    expect(
      drawer.shadowRoot.querySelector(".assistant-title").textContent
    ).toBe("Apex Analysis · Foo");
  });

  it("serves a repeat open from cache without calling the model", async () => {
    // First open generates.
    await open();
    expect(explainArtifact).toHaveBeenCalledTimes(1);

    // Same artifact and payload: the second open must not call the model.
    const second = await open();
    expect(explainArtifact).toHaveBeenCalledTimes(1);

    const rendered = second.shadowRoot.querySelector(
      ".explanation-card lightning-formatted-rich-text"
    );
    expect(rendered.value).toContain("Something");
    // Staleness is disclosed, with a way out.
    expect(second.shadowRoot.querySelector(".cache-chip").textContent).toBe(
      "cached · just now"
    );
    expect(
      [...second.shadowRoot.querySelectorAll("lightning-button")].find(
        (b) => b.label === "Re-run"
      )
    ).toBeDefined();
  });

  it("caches Explain Artifact the same way as the object audit", async () => {
    // The drawer path (diagramViewer) shares the assistant, so it shares the cache.
    await open({ artifactType: "APEX", artifactName: "MyClass" });
    expect(explainArtifact).toHaveBeenCalledTimes(1);

    await open({ artifactType: "APEX", artifactName: "MyClass" });
    expect(explainArtifact).toHaveBeenCalledTimes(1);

    // A different artifact is a different key, so it still generates.
    await open({ artifactType: "APEX", artifactName: "OtherClass" });
    expect(explainArtifact).toHaveBeenCalledTimes(2);
  });

  it("does not serve a cached result when the payload changed", async () => {
    await open({ artifactPayload: "payload A" });
    expect(explainArtifact).toHaveBeenCalledTimes(1);

    await open({ artifactPayload: "payload B" });
    expect(explainArtifact).toHaveBeenCalledTimes(2);
  });

  it("re-runs against the model when the cached result is rejected", async () => {
    await open();
    const cached = await open();
    expect(explainArtifact).toHaveBeenCalledTimes(1);

    [...cached.shadowRoot.querySelectorAll("lightning-button")]
      .find((b) => b.label === "Re-run")
      .click();
    await flushPromises();
    await flushPromises();

    // Re-run bypasses the cache rather than re-serving it.
    expect(explainArtifact).toHaveBeenCalledTimes(2);
    expect(cached.shadowRoot.querySelector(".cache-chip")).toBeNull();
  });

  it("copies the report as markdown, including both sections", async () => {
    const writeText = jest.fn().mockResolvedValue();
    Object.defineProperty(navigator, "clipboard", {
      value: { writeText },
      configurable: true
    });

    const element = await open({
      scopeSummary: "32 automations",
      verifiedFindings: "#### [HIGH] Field contention on `Rating`"
    });

    const copyBtn = [
      ...element.shadowRoot.querySelectorAll("lightning-button")
    ].find((b) => b.label === "Copy report");
    copyBtn.click();
    await flushPromises();

    const copied = writeText.mock.calls[0][0];
    expect(copied).toContain("# Automation Audit · Opportunity");
    expect(copied).toContain("32 automations");
    expect(copied).toContain("## Verified findings");
    expect(copied).toContain("Field contention on `Rating`");
    expect(copied).toContain("### Verdict");
  });
});
